#!/bin/sh
while true; do
	/usr/bin/php SendCCM1.php > logs/ccm1.log;
	/usr/bin/php SendCCM2.php > logs/ccm2.log;
	/usr/bin/php SendAKOS.php > logs/akos.log;
	/usr/bin/php SendAKP.php > logs/akp.log;
	/usr/bin/php SendDSP.php > logs/dsp.log;
	/usr/bin/php SendVOD.php > logs/vod.log;
	echo $(date "+%Y-%m-%d %H:%M:%S") main send success;
	sleep 15;
done
