
export enum SummaryAnalogSensors {
  "MODE_CTR.GAS_Q",
  "MODE_CTR.GAS_TEMPER",
  "MODE_CTR.GAS_PRESS_1",
  "MODE_CTR.GAS_PRESS_2",
  "MODE_CTR.REF_VALVE_POS",
  "MODE_CTR.VALVE_POS",
  "MODE_CTR.AIR_Q",
  "MODE_CTR.AIR_TEMPER",
  "MODE_CTR.AIR_PRESS",
  "MODE_CTR.ATM_PRESS",
  "MODE_CTR.TEMPER_COMB_GAS",
  "MODE_CTR.TEMPER_EXG",
  "MODE_CTR.RAZREGENIE",
  "MODE_CTR.ACT_TEMPER",
}
